Repository GSG-G9/dentoro, pull requests merged in 2021-04, with the labels that each got.

#35 17 post history
  server/controllers/patients/addHistoryLog/index.js
  server/controllers/patients/index.js
  server/database/config/build.sql
  server/database/queries/addHistoryLogQuery/index.js
  server/database/queries/getAppointmentsStatusByIdQuery/index.js
  server/database/queries/index.js
  server/database/queries/updateAppointmentStatusQuery/index.js
  server/routes/patients/index.js
  server/test/index.test.js
  server/utils/validation/historyLogValidation/index.js
  server/utils/validation/index.js
Labels: Awaiting Review

#37 POST /api/v1/appointments
  client/package-lock.json
  package-lock.json
  server/app.js
  server/controllers/appointments/addAppointment/index.js
  server/controllers/appointments/getAppointmentsByDate.js
  server/controllers/appointments/index.js
  server/database/queries/addAppointmentQuery/index.js
  server/database/queries/addPatientQuery/index.js
  server/database/queries/checkPatientExistence/index.js
  server/database/queries/index.js
  server/routes/appointments/index.js
  server/test/index.test.js
  server/utils/availableTimes.js
  server/utils/index.js
  server/utils/validation/appointmentDataValidation/index.js
  server/utils/validation/appointmentDateValidation/index.js
  server/utils/validation/index.js
Labels: Awaiting Review

#39 PATCH /api/v1/patients/:patientId
  server/controllers/patients/index.js
  server/controllers/patients/patchPatientData.js
  server/database/config/build.sql
  server/database/queries/index.js
  server/database/queries/patchPatientDataByIdQuery/index.js
  server/routes/patients/index.js
  server/test/index.test.js
  server/utils/validation/index.js
  server/utils/validation/patientDataValidation/index.js
Labels: Awaiting Review

#40 PATCH /api/v1/appointments/:appointmentId
  .gitignore
  package.json
  server/controllers/appointments/editAppointmentStatus/index.js
  server/controllers/appointments/editAppointmentTime/index.js
  server/controllers/appointments/index.js
  server/database/queries/index.js
  server/database/queries/updateAppointmentStatusQuery/index.js
  server/database/queries/updateAppointmentTimeQuery/index.js
  server/routes/appointments/index.js
  server/routes/patients/index.js
  server/test/index.test.js
  server/utils/validation/appointmentDateTimeValidation/index.js
  server/utils/validation/appointmentDateValidation/index.js
  server/utils/validation/appointmentStatusValidation/index.js
  server/utils/validation/index.js
Labels: Approved

#41 18 sign up
  client/package-lock.json
  package-lock.json
  server/controllers/users/addUser/index.js
  server/controllers/users/index.js
  server/database/queries/addUserQuery/index.js
  server/database/queries/checkUserIdByEmail/index.js
  server/database/queries/index.js
  server/routes/users/index.js
  server/test/index.test.js
  server/utils/jwt.js
  server/utils/validation/addUserValidation/index.js
  server/utils/validation/index.js
Labels: Awaiting Review

#44 GET /api/v1/users/logout
  server/controllers/users/index.js
  server/controllers/users/logout/index.js
  server/routes/users/index.js
  server/test/index.test.js
Labels: Approved

#45 POST /api/v1/users/login
  server/controllers/users/index.js
  server/controllers/users/login/index.js
  server/database/config/fakeData.sql
  server/database/queries/getUserDataQeury/index.js
  server/database/queries/index.js
  server/routes/users/index.js
  server/test/index.test.js
  server/utils/validation/index.js
  server/utils/validation/loginSchema/index.js
Labels: Awaiting Review

#43 Authentication Middleware
  server/controllers/users/addUser/index.js
  server/controllers/users/login/index.js
  server/middlewares/auth/index.js
  server/middlewares/index.js
  server/routes/appointments/index.js
  server/routes/index.js
  server/routes/users/index.js
  server/test/index.test.js
  server/utils/index.js
  server/utils/jwt.js
Labels: Approved

#61 Sidebar Component
  client/package-lock.json
  client/package.json
  client/src/App/index.js
  client/src/assets/images/logo.png
  client/src/components/Sidebar/index.js
  client/src/components/Sidebar/style.css
  client/src/components/common/Image/index.js
  client/src/index.js
Labels: Awaiting Review

#62 log in component and page
  client/src/App/App.css
  client/src/App/index.js
  client/src/Context/isAuthContext.js
  client/src/components/Sidebar/index.js
  client/src/components/logInForm.js
  client/src/index.css
  client/src/index.js
  client/src/pages/logIn/index.js
  client/src/pages/logIn/style.css
Labels: Approved

#64 Patients Table
  .vscode/settings.json
  client/package-lock.json
  client/package.json
  client/src/App/index.js
  client/src/components/Patients/index.js
  client/src/components/Patients/style.css
Labels: Awaiting Review

#71 add common components - AlertMessage Loading Title
  client/src/components/Sidebar/style.css
  client/src/components/common/AlertMessage/index.js
  client/src/components/common/Image/index.js
  client/src/components/common/Loading/index.js
  client/src/components/common/Loading/style.css
  client/src/components/common/Title/index.js
  client/src/components/common/Title/style.css
Labels: Approved

#63 Patient Profile Page
  client/package-lock.json
  client/package.json
  client/src/App/index.js
  client/src/components/PatientDetailsForm/index.js
  client/src/components/PatientDetailsForm/style.css
  client/src/components/PatientHistory/index.js
  client/src/components/PatientHistory/style.css
  client/src/components/PatientTreatmentForm/index.js
  client/src/components/PatientTreatmentForm/style.css
  client/src/index.css
  client/src/pages/admin/PatientProfile/index.js
  client/src/pages/admin/PatientProfile/style.css
  package-lock.json
Labels: Approved

#75 Header Component
  client/src/App/index.js
  client/src/components/Header/index.js
  client/src/components/Header/style.css
  client/src/pages/LandingPage/index.js
Labels: Awaiting Review

#82 Fix getAppointmentsByDateQuery
  server/database/queries/getAppointmentsByDateQuery/index.js
  server/test/index.test.js
Labels: bug

#81 Fix getAppointmentsByPatientName
  server/database/queries/getAppointmentsByPatientName/index.js
Labels: bug

#83 React router
  .vscode/settings.json
  client/src/App/Routes/LoggedOutRoutes.js
  client/src/App/Routes/PrivateRoutes.js
  client/src/App/Routes/index.js
  client/src/App/index.js
  client/src/Context/isAuthContext.js
  client/src/components/ADayScheduleTable/index.js
  client/src/components/PatientHistory/style.css
  client/src/components/Patients/style.css
  client/src/components/Sidebar/index.js
  client/src/components/Sidebar/style.css
  client/src/components/logInForm.js
  client/src/index.css
  client/src/index.js
  client/src/pages/logIn/index.js
Labels: Awaiting Review

#89 Router loading style
  client/src/App/App.css
  client/src/App/Routes/PrivateRoutes.js
  client/src/App/index.js
Labels: Awaiting Review

#74 Calendar Page
  client/package-lock.json
  client/src/App/Routes/LoggedOutRoutes.js
  client/src/App/index.js
  client/src/components/Calendar/index.js
  client/src/components/CalendarSearch/index.js
  client/src/components/CalendarSearch/style.css
  client/src/components/PatientHistory/style.css
  client/src/components/PatientSearchDateTable/index.js
  client/src/components/PatientSearchTable/index.js
  client/src/components/PatientSearchTable/style.css
  client/src/components/Sidebar/index.js
  client/src/pages/TodaySchedule/index.js
  client/src/pages/admin/Calendar/index.js
  client/src/pages/admin/Calendar/style.css
  client/src/pages/admin/PatientProfile/style.css
  client/src/pages/admin/PatientsAppointmentTable/index.js
Labels: In Progress

#88 Booking Form
  client/src/assets/images/booking.svg
  client/src/components/BookingForm/index.js
  client/src/components/BookingForm/style.css
  client/src/components/NavBar/index.js
  client/src/components/NavBar/style.css
  client/src/index.css
  client/src/pages/LandingPage/index.js
Labels: Awaiting Review

#95 create about us page
  client/src/assets/images/about-us-image.png
  client/src/components/BookingForm/style.css
  client/src/components/common/Image/index.js
  client/src/pages/LandingPage/index.js
  client/src/pages/LandingPage/style.css
  client/src/pages/home/AboutUs/index.js
  client/src/pages/home/AboutUs/style.css
Labels: Approved

#98 Fix Appointment table - Patient Profile
  client/src/components/PatientDetailsForm/index.js
  client/src/components/PatientSearchDateTable/index.js
  client/src/components/PatientSearchTable/index.js
  client/src/components/PatientSearchTable/style.css
Labels: bug

#96 Footer
  client/package-lock.json
  client/src/components/Footer/index.js
  client/src/components/Footer/style.css
  client/src/pages/LandingPage/index.js
  package-lock.json
Labels: Approved

#100 our sarvices
  client/src/assets/images/theme1.png
  client/src/components/OurServices/data.js
  client/src/components/OurServices/index.js
  client/src/components/OurServices/style.css
  client/src/components/ServiceCard/index.js
  client/src/components/ServiceCard/style.css
  client/src/components/header/data.js
  client/src/components/header/index.js
  client/src/components/header/style.css
  client/src/pages/LandingPage/index.js
Labels: Awaiting Review

#101 Edit Book an appointment button right margin from 11 rem to 10 rem
  client/src/components/NavBar/style.css
Labels: bug

#103 Fix Map Scroll
  client/src/components/MapComponent/index.js
Labels: bug

#105 Nav-Bar buttons fixing
  client/src/components/BookingForm/index.js
  client/src/components/MapComponent/index.js
  client/src/components/NavBar/index.js
  client/src/components/NavBar/style.css
  client/src/components/OurServices/index.js
  client/src/components/header/index.js
  client/src/components/header/style.css
  client/src/index.css
  client/src/pages/home/AboutUs/index.js
Labels: Awaiting Review

#109 Fix booking form
  client/src/components/BookingForm/index.js
  client/src/pages/logIn/style.css
Labels: bug

#107 Fix Patient Appointment Table Row Click Event
  client/src/components/PatientSearchTable/index.js
  client/src/components/PatientSearchTable/style.css
Labels: bug

#111 Home LOGO Button
  client/src/components/Patients/index.js
  client/src/components/Sidebar/index.js
Labels: Awaiting Review

#117 Fix get patients query order
  client/src/components/Calendar/index.js
  server/database/queries/getPatientsQuery/index.js
Labels: enhancement

#115 Responsive Style
  client/src/assets/images/undraw_Booking_re_gw4j.svg
  client/src/components/BookingForm/index.js
  client/src/components/BookingForm/style.css
  client/src/components/CalendarSearch/style.css
  client/src/components/MapComponent/index.js
  client/src/components/MapComponent/style.css
  client/src/components/NavBar/index.js
  client/src/components/NavBar/style.css
  client/src/components/PatientDetailsForm/style.css
  client/src/components/PatientHistory/index.js
  client/src/components/PatientSearchTable/index.js
  client/src/components/PatientSearchTable/style.css
  client/src/components/Patients/index.js
  client/src/components/Patients/style.css
  client/src/components/ServiceCard/index.js
  client/src/components/Sidebar/index.js
  client/src/components/Sidebar/style.css
  client/src/components/common/List/index.js
  client/src/components/header/index.js
  client/src/components/header/style.css
  client/src/index.css
  client/src/index.js
  client/src/pages/LandingPage/index.js
  client/src/pages/LandingPage/style.css
  client/src/pages/admin/Calendar/style.css
  client/src/pages/admin/PatientProfile/style.css
  client/src/pages/admin/PatientsAppointmentTable/index.js
  client/src/pages/home/AboutUs/style.css
  client/src/pages/home/Map/index.js
  client/src/pages/home/Map/style.css
  client/src/pages/logIn/index.js
  client/src/pages/logIn/style.css
  client/src/utils/addressInfo/index.js
Labels: Awaiting Review

#121 Fix PatientSearchValidation schema
  server/utils/validation/patientSearchValidation/index.js
Labels: Awaiting Review

#120 add search component to patients page
  client/src/components/CalendarSearch/index.js
  client/src/components/Patients/index.js
Labels: Awaiting Review

#125 make the getAvailableAppointments not auth
  server/routes/appointments/index.js
Labels: Awaiting Review

#123 Updating README file
  README.md
Labels: Awaiting Review

#126 Fix appointment search bug
  client/src/components/CalendarSearch/index.js
Labels: Awaiting Review
