Repository GSG-G9/dentoro, pull requests merged in 2021-03, with the labels that each got.

#23 File Structure
  .circleci/config.yml
  .eslintrc.json
  .gitignore
  .vscode/settings.json
  client/.eslintrc.json
  client/.gitignore
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/manifest.json
  client/public/robots.txt
  client/src/App/App.css
  client/src/App/index.js
  client/src/components/index.js
  client/src/index.css
  client/src/index.js
  client/src/logo.svg
  client/src/pages/admin/index.js
  client/src/pages/home/index.js
  client/src/utils/index.js
  package-lock.json
  package.json
  server/app.js
  server/controllers/index.js
  server/database/config/build.js
  server/database/config/build.sql
  server/database/config/connection.js
  server/database/config/fakeData.sql
  server/database/config/index.js
  server/database/queries/index.js
  server/index.js
  server/middlewares/auth/index.js
  server/middlewares/errorHandle/index.js
  server/middlewares/index.js
  server/routes/index.js
  server/test/index.js
  server/utils/index.js
  server/utils/validation/index.js
Labels: Approved

#26 README
  .vscode/settings.json
  README.md
  client/package-lock.json
  package-lock.json
  package.json
Labels: Awaiting Review

#24 7/Database connection
  .vscode/settings.json
  package.json
  server/database/config/build.js
  server/database/config/build.sql
  server/database/config/connection.js
  server/database/config/databaseConfig.sql
  server/database/config/fakeData.sql
  server/database/config/index.js
Labels: Awaiting Review

#28 Handling errors
  .vscode/settings.json
  package-lock.json
  package.json
  server/app.js
  server/middlewares/errorHandle/index.js
  server/middlewares/index.js
  server/utils/boomify.js
  server/utils/index.js
Labels: Awaiting Review

#29 GET /api/v1/appointments/:appointmentDate
  .circleci/config.yml
  package-lock.json
  package.json
  server/controllers/appointments/getAppointmentsByDate/index.js
  server/controllers/appointments/index.js
  server/database/config/build.js
  server/database/config/build.sql
  server/database/config/connection.js
  server/database/config/fakeData.sql
  server/database/config/index.js
  server/database/queries/getAppointmentsByDateQuery/index.js
  server/database/queries/index.js
  server/routes/appointments/index.js
  server/test/index.js
  server/test/index.test.js
  server/utils/index.js
  server/utils/validation/appointmentDateValidation/index.js
  server/utils/validation/index.js
Labels: Approved

#31 GET /api/v1/patients/search
  server/controllers/patients/getPatientByNameOrPhone/index.js
  server/controllers/patients/index.js
  server/database/config/fakeData.sql
  server/database/queries/getPatientByNameOrPhoneQuery/index.js
  server/database/queries/index.js
  server/routes/patients/index.js
  server/test/index.test.js
  server/utils/validation/index.js
  server/utils/validation/patientSearchValidation/index.js
Labels: Awaiting Review

#32 12 GET Patient Data By ID
  package-lock.json
  server/controllers/patients/getAllPatientData.js
  server/controllers/patients/index.js
  server/database/config/build.sql
  server/database/config/fakeData.sql
  server/database/queries/getHistoryLogs/index.js
  server/database/queries/getPatientProfileData/index.js
  server/database/queries/index.js
  server/routes/patients/index.js
  server/test/index.test.js
  server/utils/validation/index.js
  server/utils/validation/patientIdValidation/index.js
Labels: Awaiting Review

#33 21 GET Appointment Available Time
  server/controllers/appointments/getAvailableAppointments/index.js
  server/controllers/appointments/index.js
  server/database/config/fakeData.sql
  server/database/queries/getUnavailableTimes/index.js
  server/database/queries/index.js
  server/routes/appointments/index.js
  server/test/index.test.js
Labels: Approved

#34 GET /api/v1/appointments/search
  .vscode/settings.json
  package-lock.json
  server/controllers/appointments/appointmentsSearch.js
  server/controllers/appointments/getAppointmentsByDate.js
  server/controllers/appointments/index.js
  server/database/queries/getAppointmentsByPatientName/index.js
  server/database/queries/index.js
  server/routes/appointments/index.js
  server/test/index.test.js
  server/utils/validation/appointmentsSearchSchema/index.js
  server/utils/validation/index.js
Labels: Awaiting Review

#30 GET /api/v1/patients
  server/controllers/patients/getPatients.js
  server/controllers/patients/index.js
  server/database/queries/getPatientsQuery/index.js
  server/database/queries/index.js
  server/routes/patients/index.js
  server/test/index.test.js
Labels: Awaiting Review

#36 DELETE /api/v1/appointment/:appointmentId
  server/controllers/appointments/appointmentsSearch.js
  server/controllers/appointments/deleteAppointments.js
  server/controllers/appointments/index.js
  server/database/queries/deleteAppointmentsQueries/index.js
  server/database/queries/index.js
  server/middlewares/errorHandle/index.js
  server/routes/appointments/index.js
  server/routes/patients/index.js
  server/test/index.test.js
  server/utils/validation/appointmentIdValidation/index.js
  server/utils/validation/index.js
Labels: Approved

#38 DATABASE REFACTOR
  server/database/config/build.sql
  server/database/config/fakeData.sql
  server/database/queries/getHistoryLogs/index.js
  server/test/index.test.js
Labels: Epic, bug
